### ISSUE TITLE
Change the logout button

### ISSUE THREAD

**Issue by Mapsred** [TavernOfCho/website#117]
The current logout icon is not clear enough, we could use something more representative of a logout and not something that represents an eject button

I think there is an icon called logout in the material library

**Comment by AxelE** [comment]
https://material.io/tools/icons/?style=baseline any idea ?

**Comment by AxelE** [comment]
https://material.io/tools/icons/?search=exi&icon=exit_to_app&style=baseline
or https://material.io/tools/icons/?search=power&icon=power_settings_new&style=baseline

**Comment by Mapsred** [comment]
Hey @Qtipy any preference for the icon ?

**Comment by Qtipy** [comment]
https://material.io/tools/icons/?search=power&icon=power_settings_new&style=baseline
Nice one
