### ISSUE TITLE
Create offline mode

### ISSUE THREAD

**Issue by Qtipy** [TavernOfCho/website#33]
Creating offlines features for the pwa works as it should be.

**Comment by AxelE** [comment]
https://medium.com/@addyosmani/progressive-web-apps-with-react-js-part-3-offline-support-and-network-resilience-c84db889162c

**Comment by AxelE** [comment]
https://dzone.com/articles/push-notification-pwa-reactjs-using-firebase

**Comment by AxelE** [comment]
https://jakearchibald.github.io/isserviceworkerready/index.html#moar

**Comment by AxelE** [comment]
https://medium.com/@guillaumeandre/progressive-web-app-pwa-fichier-web-app-manifest-7292db378af5
D’après la spécification W3C :
Il n’existe à ce jour aucune possibilité de forcer une mise à jour du Web App Manifest de manière automatique.

**Comment by AxelE** [comment]
https://codeburst.io/how-to-add-push-notifications-on-firebase-cloud-messaging-to-react-web-app-de7c6f04c920
