### ISSUE TITLE
Touch actions

### ISSUE THREAD

**Issue by Mapsred** [TavernOfCho/website#66]
Multiple touch actions to add : 
* swap from border left to right to open menu
* swap from right to left once the menu is opened to close it
* close the menu once you click on a link on it

**Comment by AxelE** [comment]
as a samsung user, **swap from right to left** is used to screenshot my screen.
I think nobody will use this actions. But I think **close the menu once you click on a link** is a very good idea. I will take a look :eyes:

**Comment by Mapsred** [comment]
For this example, I used the Discord app as a model, when you are on a private conversation and you want to see all the private conversations you can either **use the button on top left** or **swap from left to right** to open it.

To close it, you can swap from **right to left** or **click on the opened conversation**.

You can see the same thing in many apps as Slack an many Google apps as Gmail, Agenda, Drive, ...
