### ISSUE TITLE
Intégration d'un chat

### ISSUE THREAD

**Issue by AxelE** [TavernOfCho/website#67]
Intégration d'un chat (en temps réel) à l'aide du protocole Mercure (https://mercure.rocks/) qui est un remplacement des Websockets (plus disponible sur HTTP/2)
Cette intégration de chat sera à réaliser du côté de notre API, mais aussi du côté de notre Front en React, aussi bien d'un côté technique que visuel.

**Comment by Mapsred** [comment]
https://github.com/TavernOfCho/config/issues/12
