### ISSUE TITLE
Auth - Manage expired token

### ISSUE THREAD

**Issue by Qtipy** [TavernOfCho/website#76]
For the new authentification system with Redux, need to manage when token is expired.

**Comment by Qtipy** [comment]
Auto log out on request or on location change

**Comment by Qtipy** [comment]
https://stackoverflow.com/questions/26739167/jwt-json-web-token-automatic-prolongation-of-expiration

**Comment by Mapsred** [comment]
Based on this idea, a refresh token solution was implemented in the API
For more details : https://github.com/gesdinet/JWTRefreshTokenBundle

With this, instead of implementing an auto logout, we can keep the user connected by refreshing the token once it is expired

**Comment by Qtipy** [comment]
Fixed
